Fix return error when load test not found

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -35,7 +35,12 @@ if [[ -n "$proxyHost" ]]; then
     KANGAL_PROXY_HOST="$proxyHost"
 fi
 
-loadtest=$(curl -s "http://$KANGAL_PROXY_HOST/load-test/$(urlencode "$loadtestName")" 2>/dev/null | jq -c -M .)
+loadtest=$(curl -s "http://$KANGAL_PROXY_HOST/load-test/$(urlencode "$loadtestName")" 2>/dev/null | jq -c -M . 2>/dev/null)
+
+if [[ -z "$loadtest" ]]; then
+    echo "could not get load test $loadtestName" >&2
+    exit 1
+fi
 
 version=$(\
     jq -c -M -n \
